### ISSUE TITLE
Is incompatible with KeePass version 2.54

### ISSUE THREAD

**Issue by Andrzej-Krupa** [Mascavidrio/KeePassCPEO#3]
The plugin (v1.3.0) is not working with the newest version of KeePass (2.54)
![2023-09-25 08_04_35-Window](https://github.com/quinterojose/KeePassCPEO/assets/4172737/a42248d1-bd0a-45a7-9bc5-12cca49d7bd6)

**Comment by quinterojose** [comment]
I will get it updated. Thanks for letting me know.

**Comment by quinterojose** [comment]
@Andrzej-Krupa I'm not getting the same behavior when running the plugin with 2.54. When are you seeing this dialog message? Please make sure you're using this version https://github.com/quinterojose/KeePassCPEO/releases/tag/v1.3.0

**Comment by quinterojose** [comment]
Closing this issue since it's not reproducible.
