### ISSUE TITLE
Minor Cosmetic Issue

### ISSUE THREAD

**Issue by JLWFuQrioea69ugsykvQcg** [Mascavidrio/KeePassCPEO#4]
The word "monts" is spelled incorrectly in the Custom Date Option dialog box.  It should be "Months".  Also, I'd like to suggest an option to sort the custom dates by smallest to largest or vice versa instead of basing it off the first digit of the value.

**Comment by quinterojose** [comment]
Good catch. I will get it corrected and I'll take a look at adding the sorting. Thanks.
